name: exports
description: Core exports package for Blog Store application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  bloc_signals_flutter: ^1.2.0
  dio: ^5.11.0
  firebase_analytics: ^12.4.6
  firebase_app_check: ^0.4.6
  firebase_auth: ^6.5.7
  firebase_core: ^4.13.0
  firebase_crashlytics: ^5.2.7
  firebase_messaging: ^16.5.0
  firebase_performance: ^0.11.4+6
  firebase_remote_config: ^6.5.6
  kaisel: ^1.0.0+1
  material_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  test: ^1.24.0

flutter:
  generate: true

flutter_intl:
  enabled: true
  main_locale: en
